package main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

/**
 * Created by work on 29.07.2016.
 */
public class startForm {
    private JButton unpackButton;
    private JPanel panelMain;
    private JTextField fileName;
    private JButton packButton;
    private JComboBox comboBox1;

    public startForm() {
        unpackButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                File f1 = new File(fileName.getText());
                byte[] buffer = new byte[1024];
                try (ZipInputStream zin = new ZipInputStream(new FileInputStream(fileName.getText()))) {


                    File folder = new File(f1.getParent());
                    //get the zip file content

                    //get the zipped file list entry
                    ZipEntry ze = zin.getNextEntry();

                    while (ze != null) {

                        String fileName = ze.getName();
                        File newFile = new File(f1.getParent() + File.separator + fileName);

                        System.out.println("file unzip : " + newFile.getAbsoluteFile());

                        //create all non exists folders
                        //else you will hit FileNotFoundException for compressed folder
                        new File(newFile.getParent()).mkdirs();

                        FileOutputStream fos = new FileOutputStream(newFile);

                        int len;
                        while ((len = zin.read(buffer)) > 0) {
                            fos.write(buffer, 0, len);
                        }

                        fos.close();
                        ze = zin.getNextEntry();
                    }

                    zin.closeEntry();
                    zin.close();

                    System.out.println("Done");
                    JOptionPane.showMessageDialog(panelMain, "Успешно!");


                } catch (Exception ex) {

                    System.out.println(ex.getMessage());
                }
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Mainbord compressor");
        frame.setContentPane(new startForm().panelMain);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridBagLayout());
        panelMain.setAlignmentX(0.5f);
        panelMain.setAutoscrolls(true);
        panelMain.setMinimumSize(new Dimension(500, 500));
        unpackButton = new JButton();
        unpackButton.setText("Unpack");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(unpackButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelMain.add(spacer2, gbc);
        packButton = new JButton();
        packButton.setText("Pack");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(packButton, gbc);
        comboBox1 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("zip");
        defaultComboBoxModel1.addElement("rar");
        comboBox1.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(comboBox1, gbc);
        fileName = new JTextField();
        fileName.setMinimumSize(new Dimension(400, 24));
        fileName.setText("Insert file name_____________________________");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(fileName, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }
}
